language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t mauriciomta/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mauriciomta/docker-react npm run test